// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/langfuse/terraform-provider-langfuse/internal/langfuse (interfaces: EvaluatorsClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	langfuse "github.com/langfuse/terraform-provider-langfuse/internal/langfuse"
)

// MockEvaluatorsClient is a mock of EvaluatorsClient interface.
type MockEvaluatorsClient struct {
	ctrl     *gomock.Controller
	recorder *MockEvaluatorsClientMockRecorder
}

// MockEvaluatorsClientMockRecorder is the mock recorder for MockEvaluatorsClient.
type MockEvaluatorsClientMockRecorder struct {
	mock *MockEvaluatorsClient
}

// NewMockEvaluatorsClient creates a new mock instance.
func NewMockEvaluatorsClient(ctrl *gomock.Controller) *MockEvaluatorsClient {
	mock := &MockEvaluatorsClient{ctrl: ctrl}
	mock.recorder = &MockEvaluatorsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvaluatorsClient) EXPECT() *MockEvaluatorsClientMockRecorder {
	return m.recorder
}

// CreateEvaluationRule mocks base method.
func (m *MockEvaluatorsClient) CreateEvaluationRule(arg0 context.Context, arg1 *langfuse.EvaluationRuleRequest) (*langfuse.EvaluationRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvaluationRule", arg0, arg1)
	ret0, _ := ret[0].(*langfuse.EvaluationRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvaluationRule indicates an expected call of CreateEvaluationRule.
func (mr *MockEvaluatorsClientMockRecorder) CreateEvaluationRule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvaluationRule", reflect.TypeOf((*MockEvaluatorsClient)(nil).CreateEvaluationRule), arg0, arg1)
}

// CreateEvaluator mocks base method.
func (m *MockEvaluatorsClient) CreateEvaluator(arg0 context.Context, arg1 *langfuse.EvaluatorRequest) (*langfuse.Evaluator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvaluator", arg0, arg1)
	ret0, _ := ret[0].(*langfuse.Evaluator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvaluator indicates an expected call of CreateEvaluator.
func (mr *MockEvaluatorsClientMockRecorder) CreateEvaluator(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvaluator", reflect.TypeOf((*MockEvaluatorsClient)(nil).CreateEvaluator), arg0, arg1)
}

// DeleteEvaluationRule mocks base method.
func (m *MockEvaluatorsClient) DeleteEvaluationRule(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvaluationRule", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvaluationRule indicates an expected call of DeleteEvaluationRule.
func (mr *MockEvaluatorsClientMockRecorder) DeleteEvaluationRule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvaluationRule", reflect.TypeOf((*MockEvaluatorsClient)(nil).DeleteEvaluationRule), arg0, arg1)
}

// DeleteEvaluator mocks base method.
func (m *MockEvaluatorsClient) DeleteEvaluator(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvaluator", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvaluator indicates an expected call of DeleteEvaluator.
func (mr *MockEvaluatorsClientMockRecorder) DeleteEvaluator(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvaluator", reflect.TypeOf((*MockEvaluatorsClient)(nil).DeleteEvaluator), arg0, arg1)
}

// GetEvaluationRule mocks base method.
func (m *MockEvaluatorsClient) GetEvaluationRule(arg0 context.Context, arg1 string) (*langfuse.EvaluationRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvaluationRule", arg0, arg1)
	ret0, _ := ret[0].(*langfuse.EvaluationRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvaluationRule indicates an expected call of GetEvaluationRule.
func (mr *MockEvaluatorsClientMockRecorder) GetEvaluationRule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvaluationRule", reflect.TypeOf((*MockEvaluatorsClient)(nil).GetEvaluationRule), arg0, arg1)
}

// GetEvaluator mocks base method.
func (m *MockEvaluatorsClient) GetEvaluator(arg0 context.Context, arg1 string) (*langfuse.Evaluator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvaluator", arg0, arg1)
	ret0, _ := ret[0].(*langfuse.Evaluator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvaluator indicates an expected call of GetEvaluator.
func (mr *MockEvaluatorsClientMockRecorder) GetEvaluator(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvaluator", reflect.TypeOf((*MockEvaluatorsClient)(nil).GetEvaluator), arg0, arg1)
}

// UpdateEvaluationRule mocks base method.
func (m *MockEvaluatorsClient) UpdateEvaluationRule(arg0 context.Context, arg1 string, arg2 *langfuse.EvaluationRuleRequest) (*langfuse.EvaluationRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvaluationRule", arg0, arg1, arg2)
	ret0, _ := ret[0].(*langfuse.EvaluationRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEvaluationRule indicates an expected call of UpdateEvaluationRule.
func (mr *MockEvaluatorsClientMockRecorder) UpdateEvaluationRule(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvaluationRule", reflect.TypeOf((*MockEvaluatorsClient)(nil).UpdateEvaluationRule), arg0, arg1, arg2)
}

// UpdateEvaluator mocks base method.
func (m *MockEvaluatorsClient) UpdateEvaluator(arg0 context.Context, arg1 string, arg2 *langfuse.EvaluatorRequest) (*langfuse.Evaluator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvaluator", arg0, arg1, arg2)
	ret0, _ := ret[0].(*langfuse.Evaluator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEvaluator indicates an expected call of UpdateEvaluator.
func (mr *MockEvaluatorsClientMockRecorder) UpdateEvaluator(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvaluator", reflect.TypeOf((*MockEvaluatorsClient)(nil).UpdateEvaluator), arg0, arg1, arg2)
}

// UpdateEvaluatorMetadata mocks base method.
func (m *MockEvaluatorsClient) UpdateEvaluatorMetadata(arg0 context.Context, arg1 string, arg2 *langfuse.UpdateEvaluatorMetadataRequest) (*langfuse.Evaluator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvaluatorMetadata", arg0, arg1, arg2)
	ret0, _ := ret[0].(*langfuse.Evaluator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEvaluatorMetadata indicates an expected call of UpdateEvaluatorMetadata.
func (mr *MockEvaluatorsClientMockRecorder) UpdateEvaluatorMetadata(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvaluatorMetadata", reflect.TypeOf((*MockEvaluatorsClient)(nil).UpdateEvaluatorMetadata), arg0, arg1, arg2)
}
